### ISSUE TITLE
Bug: The globPattern "undefined" did not match any files, so no file updates will be made.

### ISSUE THREAD

**Issue by pedrokost** [csantero/ember-cli-ember-leaflet#5]
Running `ember generate ember-cli-ember-leaflet` prints this:

```
ember generate ember-cli-ember-leaflet
version: 0.1.7
installing
The globPattern "undefined" did not match any files, so no file updates will be made.
Installing browser packages via Bower...
```

Using ember-cli 0.1.7

**Comment by trabus** [comment]
Sorry about this, it was [happening with any blueprint that didn't have files in it](https://github.com/ember-cli/ember-cli/issues/3142). 
The good news is, it was a benign warning, and didn't affect the install process. And the even better news is that it's gone as of ember-cli 0.1.13. 

Please feel free to close this issue.
