### ISSUE TITLE
Questions on how to use

### ISSUE THREAD

**Issue by jwo** [csantero/ember-cli-ember-leaflet#6]
I get the following error when attempting to use. I'm fairly certain I'm not using correctly, so help would be very appreciated:

> Error: Assertion Failed: undefined must be a subclass or an instance of Ember.View, not 

In the app/app.js

``` js
App.TileLayer = EmberLeaflet.TileLayer.extend({
    tileUrl: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    options: {
        attribution:
          '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
          '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
    }
});

App.Marker = EmberLeaflet.MarkerLayer.extend({});

App.MarkerCollectionLayer = EmberLeaflet.MarkerCollectionLayer.extend({
  contentBinding: "controller.model",
  itemLayerClass: App.Marker
});


App.MapView = EmberLeaflet.MapView.extend({
  zoom: 4,
  center: L.latLng(35, -96),
  childLayers: [
    App.TileLayer,
    App.MarkerCollectionLayer
  ]
});
```

In the app/templates/index.hbs

``` js
{{# view App.MapView }}{{/view}}
```
### Versions:

"DEBUG: -------------------------------" 
"DEBUG: Ember      : 1.10.0" 
"DEBUG: Ember Data : 1.0.0-beta.15"
"DEBUG: jQuery     : 1.11.2"
"DEBUG: -------------------------------"

version: 0.2.0-beta.1
node: 0.10.32
npm: 2.1.8

**Comment by csantero** [comment]
@jwo I myself haven't actually used ember-leaflet in my own projects for a while, and I don't see anything obviously wrong with your code. You might have more luck asking over on ember-leaflet.

I would recommend following the developments on https://github.com/gabesmed/ember-leaflet/tree/ember-cli-es6. They're working on turning ember-leaflet into a modern ember-cli addon, and converting the existing views into components. When that effort is complete, this repo will be deprecated.

**Comment by jwo** [comment]
@csantero ok, noted --- I tried out the branch you linked to, and while I can get the default map to show, I can't get it to use my component (so I can't do markers or layers, etc).

I'll watch over there.
